In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv(r'/home/shashu/python and data science/pokemon_data.csv')
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [14]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [16]:
df.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [17]:
df.head(6)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False

In [18]:
df.tail(2)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [19]:
df.tail(45)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
755,685,Slurpuff,Fairy,NaN,82,80,86,85,75,72,6,False
756,686,Inkay,Dark,Psychic,53,54,53,37,46,45,6,False
757,687,Malamar,Dark,Psychic,86,92,88,68,75,73,6,False
758,688,Binacle,Rock,Water,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False
760,690,Skrelp,Poison,Water,50,60,60,60,60,30,6,False
761,691,Dragalge,Poison,Dragon,65,75,90,97,123,44,6,False
762,692,Clauncher,Water,NaN,50,53,62,58,63,44,6,False
763,693,Clawitzer,Water,NaN,71,73,88,120,89,59,6,False
764,694,Helioptile,Electric,Normal,44,38,33,61,43,70,6,False
765,695,Heliolisk,Electric,Normal,62,55,52,109,94,109,6,False
766,696,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,False
767,697,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,6,False
768,698,Amaura,Rock,Ice,77,59,50,67,63,46,6,False
769,699,Aurorus,Rock,Ice,123,77,72,99,92,58,6,False
770,700,Sylveon,Fairy,NaN,95,65,65,110,130,60,6,False
771,701,Hawlucha,Fighting,Flying,78,92,75,74,63,118,6,False
772,702,Dedenne,Electric,Fairy,67,58,57,81,67,101,6,False
773,703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
774,704,Goomy,Dragon,NaN,45,50,35,55,75,40,6,False
775,705,Sliggoo,Dragon,NaN,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,90,100,70,110,150,80,6,False
777,707,Klefki,Steel,Fairy,57,80,91,80,87,75,6,False
778,708,Phantump,Ghost,Grass,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,85,100,122,58,75,54,6,False
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False
790,714,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [23]:
df.tail(4
       )

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [25]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [35]:
print(df['Name'][0:5])

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [39]:
print(df['Defense'][0:10])

0     49
1     63
2     83
3    123
4     43
5     58
6     78
7    111
8     78
9     65
Name: Defense, dtype: int64

In [41]:
print(df.values)

[[1 'Bulbasaur' 'Grass' ... 45 1 False]
 [2 'Ivysaur' 'Grass' ... 60 1 False]
 [3 'Venusaur' 'Grass' ... 80 1 False]
 ...
 [720 'HoopaHoopa Confined' 'Psychic' ... 70 6 True]
 [720 'HoopaHoopa Unbound' 'Psychic' ... 80 6 True]
 [721 'Volcanion' 'Fire' ... 70 6 True]]

In [42]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [50]:
df[['Name','Attack','Speed','Generation'][0:4]]

                      Name  Attack  Speed  Generation
0                Bulbasaur      49     45           1
1                  Ivysaur      62     60           1
2                 Venusaur      82     80           1
3    VenusaurMega Venusaur     100     80           1
4               Charmander      52     65           1
..                     ...     ...    ...         ...
795                Diancie     100     50           6
796    DiancieMega Diancie     160    110           6
797    HoopaHoopa Confined     110     70           6
798     HoopaHoopa Unbound     160     80           6
799              Volcanion     110     70           6

[800 rows x 4 columns]

In [55]:
df.iloc[1]

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [56]:
df.iloc[14]

#                  11
Name          Metapod
Type 1            Bug
Type 2            NaN
HP                 50
Attack             20
Defense            55
Sp. Atk            25
Sp. Def            25
Speed              30
Generation          1
Legendary       False
Name: 14, dtype: object

In [57]:
df.iloc[10
       ]

#                     8
Name          Wartortle
Type 1            Water
Type 2              NaN
HP                   59
Attack               63
Defense              80
Sp. Atk              65
Sp. Def              80
Speed                58
Generation            1
Legendary         False
Name: 10, dtype: object

In [58]:
df.iloc[0:6]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False

In [60]:
df.iloc[0:2]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False

In [61]:
df.iloc[1,2]

'Grass'

In [62]:
df.iloc[2,1]

'Venusaur'

In [63]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [65]:
df.iloc[798,8]

130

In [66]:
df.iloc[4,2]

'Fire'

In [71]:
for index,rows in df.iterrows():
    print(index,rows,['Type 1 '])

0 #                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object ['Type 1 ']
1 #                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object ['Type 1 ']
2 #                    3
Name          Venusaur
Type 1           Grass
Type 2          Poison
HP                  80
Attack              82
Defense             83
Sp. Atk            100
Sp. Def            100
Speed               80
Generation           1
Legendary        False
Name: 2, dtype: object ['Type 1 ']
3 #                                 3
Name          VenusaurMega Venusaur
Type 1                        Grass
Type 2                       Poison
HP                               80
Attack                          100
Defense                         123
Sp. Atk                         122
Sp. Def                         120
Speed                            80
Generation                        1
Legendary                     False
Name: 3, dtype: object ['Type 1 ']
4 #                      4
Name          Charmander
Type 1              Fire
Type 2               NaN
HP                    39
Attack                52
Defense               43
Sp. Atk               60
Sp. Def               50
Speed                 65
Generation             1
Legendary          False
Name: 4, dtype: object ['Type 1 ']
5 #                      5
Name          Charmeleon
Type 1              Fire
Type 2               NaN
HP                    58
Attack                64
Defense               58
Sp. Atk               80
Sp. Def               65
Speed                 80
Generation             1
Legendary          False
Name: 5, dtype: object ['Type 1 ']
6 #                     6
Name          Charizard
Type 1             Fire
Type 2           Flying
HP                   78
Attack               84
Defense              78
Sp. Atk             109
Sp. Def              85
Speed               100
Generation            1
Legendary         False
Name: 6, dtype: object ['Type 1 ']
7 #                                     6
Name          CharizardMega Charizard X
Type 1                             Fire
Type 2                           Dragon
HP                                   78
Attack                              130
Defense                             111
Sp. Atk                             130
Sp. Def                              85
Speed                               100
Generation                            1
Legendary                         False
Name: 7, dtype: object ['Type 1 ']
8 #                                     6
Name          CharizardMega Charizard Y
Type 1                             Fire
Type 2                           Flying
HP                                   78
Attack                              104
Defense                              78
Sp. Atk                             159
Sp. Def                             115
Speed                               100
Generation                            1
Legendary                         False
Name: 8, dtype: object ['Type 1 ']
9 #                    7
Name          Squirtle
Type 1           Water
Type 2             NaN
HP                  44
Attack              48
Defense             65
Sp. Atk             50
Sp. Def             64
Speed               43
Generation           1
Legendary        False
Name: 9, dtype: object ['Type 1 ']
10 #                     8
Name          Wartortle
Type 1            Water
Type 2              NaN
HP                   59
Attack               63
Defense              80
Sp. Atk              65
Sp. Def              80
Speed                58
Generation            1
Legendary         False
Name: 10, dtype: object ['Type 1 ']
11 #                     9
Name          Blastoise
Type 1            Water
Type 2              NaN
HP                   79
Attack               83
Defense             100
Sp. Atk              85
Sp. Def             105
Speed                78
Generation            1
Legendary         False
Name: 11, dtype: object ['Type 1 ']
12 #                                   9
Name          BlastoiseMega Blastoise
Type 1                          Water
Type 2                            NaN
HP                                 79
Attack                            103
Defense                           120
Sp. Atk                           135
Sp. Def                           115
Speed                              78
Generation                          1
Legendary                       False
Name: 12, dtype: object ['Type 1 ']
13 #                   10
Name          Caterpie
Type 1             Bug
Type 2             NaN
HP                  45
Attack              30
Defense             35
Sp. Atk             20
Sp. Def             20
Speed               45
Generation           1
Legendary        False
Name: 13, dtype: object ['Type 1 ']
14 #                  11
Name          Metapod
Type 1            Bug
Type 2            NaN
HP                 50
Attack             20
Defense            55
Sp. Atk            25
Sp. Def            25
Speed              30
Generation          1
Legendary       False
Name: 14, dtype: object ['Type 1 ']
15 #                     12
Name          Butterfree
Type 1               Bug
Type 2            Flying
HP                    60
Attack                45
Defense               50
Sp. Atk               90
Sp. Def               80
Speed                 70
Generation             1
Legendary          False
Name: 15, dtype: object ['Type 1 ']
16 #                 13
Name          Weedle
Type 1           Bug
Type 2        Poison
HP                40
Attack            35
Defense           30
Sp. Atk           20
Sp. Def           20
Speed             50
Generation         1
Legendary      False
Name: 16, dtype: object ['Type 1 ']
17 #                 14
Name          Kakuna
Type 1           Bug
Type 2        Poison
HP                45
Attack            25
Defense           50
Sp. Atk           25
Sp. Def           25
Speed             35
Generation         1
Legendary      False
Name: 17, dtype: object ['Type 1 ']
18 #                   15
Name          Beedrill
Type 1             Bug
Type 2          Poison
HP                  65
Attack              90
Defense             40
Sp. Atk             45
Sp. Def             80
Speed               75
Generation           1
Legendary        False
Name: 18, dtype: object ['Type 1 ']
19 #                                15
Name          BeedrillMega Beedrill
Type 1                          Bug
Type 2                       Poison
HP                               65
Attack                          150
Defense                          40
Sp. Atk                          15
Sp. Def                          80
Speed                           145
Generation                        1
Legendary                     False
Name: 19, dtype: object ['Type 1 ']
20 #                 16
Name          Pidgey
Type 1        Normal
Type 2        Flying
HP                40
Attack            45
Defense           40
Sp. Atk           35
Sp. Def           35
Speed             56
Generation         1
Legendary      False
Name: 20, dtype: object ['Type 1 ']
21 #                    17
Name          Pidgeotto
Type 1           Normal
Type 2           Flying
HP                   63
Attack               60
Defense              55
Sp. Atk              50
Sp. Def              50
Speed                71
Generation            1
Legendary         False
Name: 21, dtype: object ['Type 1 ']
22 #                  18
Name          Pidgeot
Type 1         Normal
Type 2         Flying
HP                 83
Attack             80
Defense            75
Sp. Atk            70
Sp. Def            70
Speed             101
Generation          1
Legendary       False
Name: 22, dtype: object ['Type 1 ']
23 #                              18
Name          PidgeotMega Pidgeot
Type 1                     Normal
Type 2                     Flying
HP                             83
Attack                         80
Defense                        80
Sp. Atk                       135
Sp. Def                        80
Speed                         121
Generation                      1
Legendary                   False
Name: 23, dtype: object ['Type 1 ']
24 #                  19
Name          Rattata
Type 1         Normal
Type 2            NaN
HP                 30
Attack             56
Defense            35
Sp. Atk            25
Sp. Def            35
Speed              72
Generation          1
Legendary       False
Name: 24, dtype: object ['Type 1 ']
25 #                   20
Name          Raticate
Type 1          Normal
Type 2             NaN
HP                  55
Attack              81
Defense             60
Sp. Atk             50
Sp. Def             70
Speed               97
Generation           1
Legendary        False
Name: 25, dtype: object ['Type 1 ']
26 #                  21
Name          Spearow
Type 1         Normal
Type 2         Flying
HP                 40
Attack             60
Defense            30
Sp. Atk            31
Sp. Def            31
Speed              70
Generation          1
Legendary       False
Name: 26, dtype: object ['Type 1 ']
27 #                 22
Name          Fearow
Type 1        Normal
Type 2        Flying
HP                65
Attack            90
Defense           65
Sp. Atk           61
Sp. Def           61
Speed            100
Generation         1
Legendary      False
Name: 27, dtype: object ['Type 1 ']
28 #                 23
Name           Ekans
Type 1        Poison
Type 2           NaN
HP                35
Attack            60
Defense           44
Sp. Atk           40
Sp. Def           54
Speed             55
Generation         1
Legendary      False
Name: 28, dtype: object ['Type 1 ']
29 #                 24
Name           Arbok
Type 1        Poison
Type 2           NaN
HP                60
Attack            85
Defense           69
Sp. Atk           65
Sp. Def           79
Speed             80
Generation         1
Legendary      False
Name: 29, dtype: object ['Type 1 ']
30 #                   25
Name           Pikachu
Type 1        Electric
Type 2             NaN
HP                  35
Attack              55
Defense             40
Sp. Atk             50
Sp. Def             50
Speed               90
Generation           1
Legendary        False
Name: 30, dtype: object ['Type 1 ']
31 #                   26
Name            Raichu
Type 1        Electric
Type 2             NaN
HP                  60
Attack              90
Defense             55
Sp. Atk             90
Sp. Def             80
Speed              110
Generation           1
Legendary        False
Name: 31, dtype: object ['Type 1 ']
32 #                    27
Name          Sandshrew
Type 1           Ground
Type 2              NaN
HP                   50
Attack               75
Defense              85
Sp. Atk              20
Sp. Def              30
Speed                40
Generation            1
Legendary         False
Name: 32, dtype: object ['Type 1 ']
33 #                    28
Name          Sandslash
Type 1           Ground
Type 2              NaN
HP                   75
Attack              100
Defense             110
Sp. Atk              45
Sp. Def              55
Speed                65
Generation            1
Legendary         False
Name: 33, dtype: object ['Type 1 ']
34 #                           29
Name          Nidoran (Female)
Type 1                  Poison
Type 2                     NaN
HP                          55
Attack                      47
Defense                     52
Sp. Atk                     40
Sp. Def                     40
Speed                       41
Generation                   1
Legendary                False
Name: 34, dtype: object ['Type 1 ']
35 #                   30
Name          Nidorina
Type 1          Poison
Type 2             NaN
HP                  70
Attack              62
Defense             67
Sp. Atk             55
Sp. Def             55
Speed               56
Generation           1
Legendary        False
Name: 35, dtype: object ['Type 1 ']
36 #                    31
Name          Nidoqueen
Type 1           Poison
Type 2           Ground
HP                   90
Attack               92
Defense              87
Sp. Atk              75
Sp. Def              85
Speed                76
Generation            1
Legendary         False
Name: 36, dtype: object ['Type 1 ']
37 #                         32
Name          Nidoran (Male)
Type 1                Poison
Type 2                   NaN
HP                        46
Attack                    57
Defense                   40
Sp. Atk                   40
Sp. Def                   40
Speed                     50
Generation                 1
Legendary              False
Name: 37, dtype: object ['Type 1 ']
38 #                   33
Name          Nidorino
Type 1          Poison
Type 2             NaN
HP                  61
Attack              72
Defense             57
Sp. Atk             55
Sp. Def             55
Speed               65
Generation           1
Legendary        False
Name: 38, dtype: object ['Type 1 ']
39 #                   34
Name          Nidoking
Type 1          Poison
Type 2          Ground
HP                  81
Attack             102
Defense             77
Sp. Atk             85
Sp. Def             75
Speed               85
Generation           1
Legendary        False
Name: 39, dtype: object ['Type 1 ']
40 #                   35
Name          Clefairy
Type 1           Fairy
Type 2             NaN
HP                  70
Attack              45
Defense             48
Sp. Atk             60
Sp. Def             65
Speed               35
Generation           1
Legendary        False
Name: 40, dtype: object ['Type 1 ']
41 #                   36
Name          Clefable
Type 1           Fairy
Type 2             NaN
HP                  95
Attack              70
Defense             73
Sp. Atk             95
Sp. Def             90
Speed               60
Generation           1
Legendary        False
Name: 41, dtype: object ['Type 1 ']
42 #                 37
Name          Vulpix
Type 1          Fire
Type 2           NaN
HP                38
Attack            41
Defense           40
Sp. Atk           50
Sp. Def           65
Speed             65
Generation         1
Legendary      False
Name: 42, dtype: object ['Type 1 ']
43 #                    38
Name          Ninetales
Type 1             Fire
Type 2              NaN
HP                   73
Attack               76
Defense              75
Sp. Atk              81
Sp. Def             100
Speed               100
Generation            1
Legendary         False
Name: 43, dtype: object ['Type 1 ']
44 #                     39
Name          Jigglypuff
Type 1            Normal
Type 2             Fairy
HP                   115
Attack                45
Defense               20
Sp. Atk               45
Sp. Def               25
Speed                 20
Generation             1
Legendary          False
Name: 44, dtype: object ['Type 1 ']
45 #                     40
Name          Wigglytuff
Type 1            Normal
Type 2             Fairy
HP                   140
Attack                70
Defense               45
Sp. Atk               85
Sp. Def               50
Speed                 45
Generation             1
Legendary          False
Name: 45, dtype: object ['Type 1 ']
46 #                 41
Name           Zubat
Type 1        Poison
Type 2        Flying
HP                40
Attack            45
Defense           35
Sp. Atk           30
Sp. Def           40
Speed             55
Generation         1
Legendary      False
Name: 46, dtype: object ['Type 1 ']
47 #                 42
Name          Golbat
Type 1        Poison
Type 2        Flying
HP                75
Attack            80
Defense           70
Sp. Atk           65
Sp. Def           75
Speed             90
Generation         1
Legendary      False
Name: 47, dtype: object ['Type 1 ']
48 #                 43
Name          Oddish
Type 1         Grass
Type 2        Poison
HP                45
Attack            50
Defense           55
Sp. Atk           75
Sp. Def           65
Speed             30
Generation         1
Legendary      False
Name: 48, dtype: object ['Type 1 ']
49 #                 44
Name           Gloom
Type 1         Grass
Type 2        Poison
HP                60
Attack            65
Defense           70
Sp. Atk           85
Sp. Def           75
Speed             40
Generation         1
Legendary      False
Name: 49, dtype: object ['Type 1 ']
50 #                    45
Name          Vileplume
Type 1            Grass
Type 2           Poison
HP                   75
Attack               80
Defense              85
Sp. Atk             110
Sp. Def              90
Speed                50
Generation            1
Legendary         False
Name: 50, dtype: object ['Type 1 ']
51 #                46
Name          Paras
Type 1          Bug
Type 2        Grass
HP               35
Attack           70
Defense          55
Sp. Atk          45
Sp. Def          55
Speed            25
Generation        1
Legendary     False
Name: 51, dtype: object ['Type 1 ']
52 #                   47
Name          Parasect
Type 1             Bug
Type 2           Grass
HP                  60
Attack              95
Defense             80
Sp. Atk             60
Sp. Def             80
Speed               30
Generation           1
Legendary        False
Name: 52, dtype: object ['Type 1 ']
53 #                  48
Name          Venonat
Type 1            Bug
Type 2         Poison
HP                 60
Attack             55
Defense            50
Sp. Atk            40
Sp. Def            55
Speed              45
Generation          1
Legendary       False
Name: 53, dtype: object ['Type 1 ']
54 #                   49
Name          Venomoth
Type 1             Bug
Type 2          Poison
HP                  70
Attack              65
Defense             60
Sp. Atk             90
Sp. Def             75
Speed               90
Generation           1
Legendary        False
Name: 54, dtype: object ['Type 1 ']
55 #                  50
Name          Diglett
Type 1         Ground
Type 2            NaN
HP                 10
Attack             55
Defense            25
Sp. Atk            35
Sp. Def            45
Speed              95
Generation          1
Legendary       False
Name: 55, dtype: object ['Type 1 ']
56 #                  51
Name          Dugtrio
Type 1         Ground
Type 2            NaN
HP                 35
Attack             80
Defense            50
Sp. Atk            50
Sp. Def            70
Speed             120
Generation          1
Legendary       False
Name: 56, dtype: object ['Type 1 ']
57 #                 52
Name          Meowth
Type 1        Normal
Type 2           NaN
HP                40
Attack            45
Defense           35
Sp. Atk           40
Sp. Def           40
Speed             90
Generation         1
Legendary      False
Name: 57, dtype: object ['Type 1 ']
58 #                  53
Name          Persian
Type 1         Normal
Type 2            NaN
HP                 65
Attack             70
Defense            60
Sp. Atk            65
Sp. Def            65
Speed             115
Generation          1
Legendary       False
Name: 58, dtype: object ['Type 1 ']
59 #                  54
Name          Psyduck
Type 1          Water
Type 2            NaN
HP                 50
Attack             52
Defense            48
Sp. Atk            65
Sp. Def            50
Speed              55
Generation          1
Legendary       False
Name: 59, dtype: object ['Type 1 ']
60 #                  55
Name          Golduck
Type 1          Water
Type 2            NaN
HP                 80

Name: 230, dtype: object ['Type 1 ']
231 #                   214
Name          Heracross
Type 1              Bug
Type 2         Fighting
HP                   80
Attack              125
Defense              75
Sp. Atk              40
Sp. Def              95
Speed                85
Generation            2
Legendary         False
Name: 231, dtype: object ['Type 1 ']
232 #                                 214
Name          HeracrossMega Heracross
Type 1                            Bug
Type 2                       Fighting
HP                                 80
Attack                            185
Defense                           115
Sp. Atk                            40
Sp. Def                           105
Speed                              75
Generation                          2
Legendary                       False
Name: 232, dtype: object ['Type 1 ']
233 #                 215
Name          Sneasel
Type 1           Dark
Type 2            Ice
HP                 55
Attack             95
Defense            55
Sp. Atk            35
Sp. Def            75
Speed             115
Generation          2
Legendary       False
Name: 233, dtype: object ['Type 1 ']
234 #                   216
Name          Teddiursa
Type 1           Normal
Type 2              NaN
HP                   60
Attack               80
Defense              50
Sp. Atk              50
Sp. Def              50
Speed                40
Generation            2
Legendary         False
Name: 234, dtype: object ['Type 1 ']
235 #                  217
Name          Ursaring
Type 1          Normal
Type 2             NaN
HP                  90
Attack             130
Defense             75
Sp. Atk             75
Sp. Def             75
Speed               55
Generation           2
Legendary        False
Name: 235, dtype: object ['Type 1 ']
236 #                218
Name          Slugma
Type 1          Fire
Type 2           NaN
HP                40
Attack            40
Defense           40
Sp. Atk           70
Sp. Def           40
Speed             20
Generation         2
Legendary      False
Name: 236, dtype: object ['Type 1 ']
237 #                  219
Name          Magcargo
Type 1            Fire
Type 2            Rock
HP                  50
Attack              50
Defense            120
Sp. Atk             80
Sp. Def             80
Speed               30
Generation           2
Legendary        False
Name: 237, dtype: object ['Type 1 ']
238 #                220
Name          Swinub
Type 1           Ice
Type 2        Ground
HP                50
Attack            50
Defense           40
Sp. Atk           30
Sp. Def           30
Speed             50
Generation         2
Legendary      False
Name: 238, dtype: object ['Type 1 ']
239 #                   221
Name          Piloswine
Type 1              Ice
Type 2           Ground
HP                  100
Attack              100
Defense              80
Sp. Atk              60
Sp. Def              60
Speed                50
Generation            2
Legendary         False
Name: 239, dtype: object ['Type 1 ']
240 #                 222
Name          Corsola
Type 1          Water
Type 2           Rock
HP                 55
Attack             55
Defense            85
Sp. Atk            65
Sp. Def            85
Speed              35
Generation          2
Legendary       False
Name: 240, dtype: object ['Type 1 ']
241 #                  223
Name          Remoraid
Type 1           Water
Type 2             NaN
HP                  35
Attack              65
Defense             35
Sp. Atk             65
Sp. Def             35
Speed               65
Generation           2
Legendary        False
Name: 241, dtype: object ['Type 1 ']
242 #                   224
Name          Octillery
Type 1            Water
Type 2              NaN
HP                   75
Attack              105
Defense              75
Sp. Atk             105
Sp. Def              75
Speed                45
Generation            2
Legendary         False
Name: 242, dtype: object ['Type 1 ']
243 #                  225
Name          Delibird
Type 1             Ice
Type 2          Flying
HP                  45
Attack              55
Defense             45
Sp. Atk             65
Sp. Def             45
Speed               75
Generation           2
Legendary        False
Name: 243, dtype: object ['Type 1 ']
244 #                 226
Name          Mantine
Type 1          Water
Type 2         Flying
HP                 65
Attack             40
Defense            70
Sp. Atk            80
Sp. Def           140
Speed              70
Generation          2
Legendary       False
Name: 244, dtype: object ['Type 1 ']
245 #                  227
Name          Skarmory
Type 1           Steel
Type 2          Flying
HP                  65
Attack              80
Defense            140
Sp. Atk             40
Sp. Def             70
Speed               70
Generation           2
Legendary        False
Name: 245, dtype: object ['Type 1 ']
246 #                  228
Name          Houndour
Type 1            Dark
Type 2            Fire
HP                  45
Attack              60
Defense             30
Sp. Atk             80
Sp. Def             50
Speed               65
Generation           2
Legendary        False
Name: 246, dtype: object ['Type 1 ']
247 #                  229
Name          Houndoom
Type 1            Dark
Type 2            Fire
HP                  75
Attack              90
Defense             50
Sp. Atk            110
Sp. Def             80
Speed               95
Generation           2
Legendary        False
Name: 247, dtype: object ['Type 1 ']
248 #                               229
Name          HoundoomMega Houndoom
Type 1                         Dark
Type 2                         Fire
HP                               75
Attack                           90
Defense                          90
Sp. Atk                         140
Sp. Def                          90
Speed                           115
Generation                        2
Legendary                     False
Name: 248, dtype: object ['Type 1 ']
249 #                 230
Name          Kingdra
Type 1          Water
Type 2         Dragon
HP                 75
Attack             95
Defense            95
Sp. Atk            95
Sp. Def            95
Speed              85
Generation          2
Legendary       False
Name: 249, dtype: object ['Type 1 ']
250 #                231
Name          Phanpy
Type 1        Ground
Type 2           NaN
HP                90
Attack            60
Defense           60
Sp. Atk           40
Sp. Def           40
Speed             40
Generation         2
Legendary      False
Name: 250, dtype: object ['Type 1 ']
251 #                 232
Name          Donphan
Type 1         Ground
Type 2            NaN
HP                 90
Attack            120
Defense           120
Sp. Atk            60
Sp. Def            60
Speed              50
Generation          2
Legendary       False
Name: 251, dtype: object ['Type 1 ']
252 #                  233
Name          Porygon2
Type 1          Normal
Type 2             NaN
HP                  85
Attack              80
Defense             90
Sp. Atk            105
Sp. Def             95
Speed               60
Generation           2
Legendary        False
Name: 252, dtype: object ['Type 1 ']
253 #                  234
Name          Stantler
Type 1          Normal
Type 2             NaN
HP                  73
Attack              95
Defense             62
Sp. Atk             85
Sp. Def             65
Speed               85
Generation           2
Legendary        False
Name: 253, dtype: object ['Type 1 ']
254 #                  235
Name          Smeargle
Type 1          Normal
Type 2             NaN
HP                  55
Attack              20
Defense             35
Sp. Atk             20
Sp. Def             45
Speed               75
Generation           2
Legendary        False
Name: 254, dtype: object ['Type 1 ']
255 #                  236
Name           Tyrogue
Type 1        Fighting
Type 2             NaN
HP                  35
Attack              35
Defense             35
Sp. Atk             35
Sp. Def             35
Speed               35
Generation           2
Legendary        False
Name: 255, dtype: object ['Type 1 ']
256 #                   237
Name          Hitmontop
Type 1         Fighting
Type 2              NaN
HP                   50
Attack               95
Defense              95
Sp. Atk              35
Sp. Def             110
Speed                70
Generation            2
Legendary         False
Name: 256, dtype: object ['Type 1 ']
257 #                  238
Name          Smoochum
Type 1             Ice
Type 2         Psychic
HP                  45
Attack              30
Defense             15
Sp. Atk             85
Sp. Def             65
Speed               65
Generation           2
Legendary        False
Name: 257, dtype: object ['Type 1 ']
258 #                  239
Name            Elekid
Type 1        Electric
Type 2             NaN
HP                  45
Attack              63
Defense             37
Sp. Atk             65
Sp. Def             55
Speed               95
Generation           2
Legendary        False
Name: 258, dtype: object ['Type 1 ']
259 #               240
Name          Magby
Type 1         Fire
Type 2          NaN
HP               45
Attack           75
Defense          37
Sp. Atk          70
Sp. Def          55
Speed            83
Generation        2
Legendary     False
Name: 259, dtype: object ['Type 1 ']
260 #                 241
Name          Miltank
Type 1         Normal
Type 2            NaN
HP                 95
Attack             80
Defense           105
Sp. Atk            40
Sp. Def            70
Speed             100
Generation          2
Legendary       False
Name: 260, dtype: object ['Type 1 ']
261 #                 242
Name          Blissey
Type 1         Normal
Type 2            NaN
HP                255
Attack             10
Defense            10
Sp. Atk            75
Sp. Def           135
Speed              55
Generation          2
Legendary       False
Name: 261, dtype: object ['Type 1 ']
262 #                  243
Name            Raikou
Type 1        Electric
Type 2             NaN
HP                  90
Attack              85
Defense             75
Sp. Atk            115
Sp. Def            100
Speed              115
Generation           2
Legendary         True
Name: 262, dtype: object ['Type 1 ']
263 #               244
Name          Entei
Type 1         Fire
Type 2          NaN
HP              115
Attack          115
Defense          85
Sp. Atk          90
Sp. Def          75
Speed           100
Generation        2
Legendary      True
Name: 263, dtype: object ['Type 1 ']
264 #                 245
Name          Suicune
Type 1          Water
Type 2            NaN
HP                100
Attack             75
Defense           115
Sp. Atk            90
Sp. Def           115
Speed              85
Generation          2
Legendary        True
Name: 264, dtype: object ['Type 1 ']
265 #                  246
Name          Larvitar
Type 1            Rock
Type 2          Ground
HP                  50
Attack              64
Defense             50
Sp. Atk             45
Sp. Def             50
Speed               41
Generation           2
Legendary        False
Name: 265, dtype: object ['Type 1 ']
266 #                 247
Name          Pupitar
Type 1           Rock
Type 2         Ground
HP                 70
Attack             84
Defense            70
Sp. Atk            65
Sp. Def            70
Speed              51
Generation          2
Legendary       False
Name: 266, dtype: object ['Type 1 ']
267 #                   248
Name          Tyranitar
Type 1             Rock
Type 2             Dark
HP                  100
Attack              134
Defense             110
Sp. Atk              95
Sp. Def             100
Speed                61
Generation            2
Legendary         False
Name: 267, dtype: object ['Type 1 ']
268 #                                 248
Name          TyranitarMega Tyranitar
Type 1                           Rock
Type 2                           Dark
HP                                100
Attack                            164
Defense                           150
Sp. Atk                            95
Sp. Def                           120
Speed                              71
Generation                          2
Legendary                       False
Name: 268, dtype: object ['Type 1 ']
269 #                 249
Name            Lugia
Type 1        Psychic
Type 2         Flying
HP                106
Attack             90
Defense           130
Sp. Atk            90
Sp. Def           154
Speed             110
Generation          2
Legendary        True
Name: 269, dtype: object ['Type 1 ']
270 #                250
Name           Ho-oh
Type 1          Fire
Type 2        Flying
HP               106
Attack           130
Defense           90
Sp. Atk          110
Sp. Def          154
Speed             90
Generation         2
Legendary       True
Name: 270, dtype: object ['Type 1 ']
271 #                 251
Name           Celebi
Type 1        Psychic
Type 2          Grass
HP                100
Attack            100
Defense           100
Sp. Atk           100
Sp. Def           100
Speed             100
Generation          2
Legendary       False
Name: 271, dtype: object ['Type 1 ']
272 #                 252
Name          Treecko
Type 1          Grass
Type 2            NaN
HP                 40
Attack             45
Defense            35
Sp. Atk            65
Sp. Def            55
Speed              70
Generation          3
Legendary       False
Name: 272, dtype: object ['Type 1 ']
273 #                 253
Name          Grovyle
Type 1          Grass
Type 2            NaN
HP                 50
Attack             65
Defense            45
Sp. Atk            85
Sp. Def            65
Speed              95
Generation          3
Legendary       False
Name: 273, dtype: object ['Type 1 ']
274 #                  254
Name          Sceptile
Type 1           Grass
Type 2             NaN
HP                  70
Attack              85
Defense             65
Sp. Atk            105
Sp. Def             85
Speed              120
Generation           3
Legendary        False
Name: 274, dtype: object ['Type 1 ']
275 #                               254
Name          SceptileMega Sceptile
Type 1                        Grass
Type 2                       Dragon
HP                               70
Attack                          110
Defense                          75
Sp. Atk                         145
Sp. Def                          85
Speed                           145
Generation                        3
Legendary                     False
Name: 275, dtype: object ['Type 1 ']
276 #                 255
Name          Torchic
Type 1           Fire
Type 2            NaN
HP                 45
Attack             60
Defense            40
Sp. Atk            70
Sp. Def            50
Speed              45
Generation          3
Legendary       False
Name: 276, dtype: object ['Type 1 ']
277 #                   256
Name          Combusken
Type 1             Fire
Type 2         Fighting
HP                   60
Attack               85
Defense              60
Sp. Atk              85
Sp. Def              60
Speed                55
Generation            3
Legendary         False
Name: 277, dtype: object ['Type 1 ']
278 #                  257
Name          Blaziken
Type 1            Fire
Type 2        Fighting
HP                  80
Attack             120
Defense             70
Sp. Atk            110
Sp. Def             70
Speed               80
Generation           3
Legendary        False
Name: 278, dtype: object ['Type 1 ']
279 #                               257
Name          BlazikenMega Blaziken
Type 1                         Fire
Type 2                     Fighting
HP                               80
Attack                          160
Defense                          80
Sp. Atk                         130
Sp. Def                          80
Speed                           100
Generation                        3
Legendary                     False
Name: 279, dtype: object ['Type 1 ']
280 #                258
Name          Mudkip
Type 1         Water
Type 2           NaN
HP                50
Attack            70
Defense           50
Sp. Atk           50
Sp. Def           50
Speed             40
Generation         3
Legendary      False
Name: 280, dtype: object ['Type 1 ']
281 #                   259
Name          Marshtomp
Type 1            Water
Type 2           Ground
HP                   70
Attack               85
Defense              70
Sp. Atk              60
Sp. Def              70
Speed                50
Generation            3
Legendary         False
Name: 281, dtype: object ['Type 1 ']
282 #                  260
Name          Swampert
Type 1           Water
Type 2          Ground
HP                 100
Attack             110
Defense             90
Sp. Atk             85
Sp. Def             90
Speed               60
Generation           3
Legendary        False
Name: 282, dtype: object ['Type 1 ']
283 #                               260
Name          SwampertMega Swampert
Type 1                        Water
Type 2                       Ground
HP                              100
Attack                          150
Defense                         110
Sp. Atk                          95
Sp. Def                         110
Speed                            70
Generation                        3
Legendary                     False
Name: 283, dtype: object ['Type 1 ']
284 #                   261
Name          Poochyena
Type 1             Dark
Type 2              NaN
HP                   35
Attack               55
Defense              35
Sp. Atk              30
Sp. Def              30
Speed                35
Generation            3
Legendary         False
Name: 284, dtype: object ['Type 1 ']
285 #                   262
Name          Mightyena
Type 1             Dark
Type 2              NaN
HP                   70
Attack               90
Defense              70
Sp. Atk              60
Sp. Def              60
Speed                70
Generation            3
Legendary         False
Name: 285, dtype: object ['Type 1 ']
286 #                   263
Name          Zigzagoon
Type 1           Normal
Type 2              NaN
HP                   38
Attack               30
Defense              41
Sp. Atk              30
Sp. Def              41
Speed                60
Generation            3
Legendary         False
Name: 286, dtype: object ['Type 1 ']
287 #                 264
Name          Linoone
Type 1         Normal
Type 2            NaN
HP                 78
Attack             70
Defense            61
Sp. Atk            50
Sp. Def            61
Speed             100
Generation          3
Legendary       False
Name: 287, dtype: object ['Type 1 ']
288 #                 265
Name          Wurmple
Type 1            Bug
Type 2            NaN
HP                 45
Attack             45
Defense            35
Sp. Atk            20
Sp. Def            30
Speed              20
Generation          3
Legendary       False
Name: 288, dtype: object ['Type 1 ']
289 #                 266
Name          Silcoon
Type 1            Bug
Type 2            NaN
HP                 50
Attack             35
Defense            55
Sp. Atk            25
Sp. Def            25
Speed              15
Generation          3
Legendary       False
Name: 289, dtype: object ['Type 1 ']
290 #                   267
Name          Beautifly
Type 1              Bug
Type 2           Flying
HP                   60
Attack               70
Defense              50
Sp. Atk             100
Sp. Def              50
Speed                65
Generation            3
Legendary         False
Name: 290, dtype: object ['Type 1 ']
291 #                 268
Name          Cascoon
Type 1            Bug
Type 2            NaN
HP                 50
Attack             35
Defense            55
Sp. Atk            25
Sp. Def            25

Name: 467, dtype: object ['Type 1 ']
468 #                 421
Name          Cherrim
Type 1          Grass
Type 2            NaN
HP                 70
Attack             60
Defense            70
Sp. Atk            87
Sp. Def            78
Speed              85
Generation          4
Legendary       False
Name: 468, dtype: object ['Type 1 ']
469 #                 422
Name          Shellos
Type 1          Water
Type 2            NaN
HP                 76
Attack             48
Defense            48
Sp. Atk            57
Sp. Def            62
Speed              34
Generation          4
Legendary       False
Name: 469, dtype: object ['Type 1 ']
470 #                   423
Name          Gastrodon
Type 1            Water
Type 2           Ground
HP                  111
Attack               83
Defense              68
Sp. Atk              92
Sp. Def              82
Speed                39
Generation            4
Legendary         False
Name: 470, dtype: object ['Type 1 ']
471 #                 424
Name          Ambipom
Type 1         Normal
Type 2            NaN
HP                 75
Attack            100
Defense            66
Sp. Atk            60
Sp. Def            66
Speed             115
Generation          4
Legendary       False
Name: 471, dtype: object ['Type 1 ']
472 #                  425
Name          Drifloon
Type 1           Ghost
Type 2          Flying
HP                  90
Attack              50
Defense             34
Sp. Atk             60
Sp. Def             44
Speed               70
Generation           4
Legendary        False
Name: 472, dtype: object ['Type 1 ']
473 #                  426
Name          Drifblim
Type 1           Ghost
Type 2          Flying
HP                 150
Attack              80
Defense             44
Sp. Atk             90
Sp. Def             54
Speed               80
Generation           4
Legendary        False
Name: 473, dtype: object ['Type 1 ']
474 #                 427
Name          Buneary
Type 1         Normal
Type 2            NaN
HP                 55
Attack             66
Defense            44
Sp. Atk            44
Sp. Def            56
Speed              85
Generation          4
Legendary       False
Name: 474, dtype: object ['Type 1 ']
475 #                 428
Name          Lopunny
Type 1         Normal
Type 2            NaN
HP                 65
Attack             76
Defense            84
Sp. Atk            54
Sp. Def            96
Speed             105
Generation          4
Legendary       False
Name: 475, dtype: object ['Type 1 ']
476 #                             428
Name          LopunnyMega Lopunny
Type 1                     Normal
Type 2                   Fighting
HP                             65
Attack                        136
Defense                        94
Sp. Atk                        54
Sp. Def                        96
Speed                         135
Generation                      4
Legendary                   False
Name: 476, dtype: object ['Type 1 ']
477 #                   429
Name          Mismagius
Type 1            Ghost
Type 2              NaN
HP                   60
Attack               60
Defense              60
Sp. Atk             105
Sp. Def             105
Speed               105
Generation            4
Legendary         False
Name: 477, dtype: object ['Type 1 ']
478 #                   430
Name          Honchkrow
Type 1             Dark
Type 2           Flying
HP                  100
Attack              125
Defense              52
Sp. Atk             105
Sp. Def              52
Speed                71
Generation            4
Legendary         False
Name: 478, dtype: object ['Type 1 ']
479 #                 431
Name          Glameow
Type 1         Normal
Type 2            NaN
HP                 49
Attack             55
Defense            42
Sp. Atk            42
Sp. Def            37
Speed              85
Generation          4
Legendary       False
Name: 479, dtype: object ['Type 1 ']
480 #                 432
Name          Purugly
Type 1         Normal
Type 2            NaN
HP                 71
Attack             82
Defense            64
Sp. Atk            64
Sp. Def            59
Speed             112
Generation          4
Legendary       False
Name: 480, dtype: object ['Type 1 ']
481 #                   433
Name          Chingling
Type 1          Psychic
Type 2              NaN
HP                   45
Attack               30
Defense              50
Sp. Atk              65
Sp. Def              50
Speed                45
Generation            4
Legendary         False
Name: 481, dtype: object ['Type 1 ']
482 #                434
Name          Stunky
Type 1        Poison
Type 2          Dark
HP                63
Attack            63
Defense           47
Sp. Atk           41
Sp. Def           41
Speed             74
Generation         4
Legendary      False
Name: 482, dtype: object ['Type 1 ']
483 #                  435
Name          Skuntank
Type 1          Poison
Type 2            Dark
HP                 103
Attack              93
Defense             67
Sp. Atk             71
Sp. Def             61
Speed               84
Generation           4
Legendary        False
Name: 483, dtype: object ['Type 1 ']
484 #                 436
Name          Bronzor
Type 1          Steel
Type 2        Psychic
HP                 57
Attack             24
Defense            86
Sp. Atk            24
Sp. Def            86
Speed              23
Generation          4
Legendary       False
Name: 484, dtype: object ['Type 1 ']
485 #                  437
Name          Bronzong
Type 1           Steel
Type 2         Psychic
HP                  67
Attack              89
Defense            116
Sp. Atk             79
Sp. Def            116
Speed               33
Generation           4
Legendary        False
Name: 485, dtype: object ['Type 1 ']
486 #                438
Name          Bonsly
Type 1          Rock
Type 2           NaN
HP                50
Attack            80
Defense           95
Sp. Atk           10
Sp. Def           45
Speed             10
Generation         4
Legendary      False
Name: 486, dtype: object ['Type 1 ']
487 #                  439
Name          Mime Jr.
Type 1         Psychic
Type 2           Fairy
HP                  20
Attack              25
Defense             45
Sp. Atk             70
Sp. Def             90
Speed               60
Generation           4
Legendary        False
Name: 487, dtype: object ['Type 1 ']
488 #                 440
Name          Happiny
Type 1         Normal
Type 2            NaN
HP                100
Attack              5
Defense             5
Sp. Atk            15
Sp. Def            65
Speed              30
Generation          4
Legendary       False
Name: 488, dtype: object ['Type 1 ']
489 #                441
Name          Chatot
Type 1        Normal
Type 2        Flying
HP                76
Attack            65
Defense           45
Sp. Atk           92
Sp. Def           42
Speed             91
Generation         4
Legendary      False
Name: 489, dtype: object ['Type 1 ']
490 #                   442
Name          Spiritomb
Type 1            Ghost
Type 2             Dark
HP                   50
Attack               92
Defense             108
Sp. Atk              92
Sp. Def             108
Speed                35
Generation            4
Legendary         False
Name: 490, dtype: object ['Type 1 ']
491 #                443
Name           Gible
Type 1        Dragon
Type 2        Ground
HP                58
Attack            70
Defense           45
Sp. Atk           40
Sp. Def           45
Speed             42
Generation         4
Legendary      False
Name: 491, dtype: object ['Type 1 ']
492 #                444
Name          Gabite
Type 1        Dragon
Type 2        Ground
HP                68
Attack            90
Defense           65
Sp. Atk           50
Sp. Def           55
Speed             82
Generation         4
Legendary      False
Name: 492, dtype: object ['Type 1 ']
493 #                  445
Name          Garchomp
Type 1          Dragon
Type 2          Ground
HP                 108
Attack             130
Defense             95
Sp. Atk             80
Sp. Def             85
Speed              102
Generation           4
Legendary        False
Name: 493, dtype: object ['Type 1 ']
494 #                               445
Name          GarchompMega Garchomp
Type 1                       Dragon
Type 2                       Ground
HP                              108
Attack                          170
Defense                         115
Sp. Atk                         120
Sp. Def                          95
Speed                            92
Generation                        4
Legendary                     False
Name: 494, dtype: object ['Type 1 ']
495 #                  446
Name          Munchlax
Type 1          Normal
Type 2             NaN
HP                 135
Attack              85
Defense             40
Sp. Atk             40
Sp. Def             85
Speed                5
Generation           4
Legendary        False
Name: 495, dtype: object ['Type 1 ']
496 #                  447
Name             Riolu
Type 1        Fighting
Type 2             NaN
HP                  40
Attack              70
Defense             40
Sp. Atk             35
Sp. Def             40
Speed               60
Generation           4
Legendary        False
Name: 496, dtype: object ['Type 1 ']
497 #                  448
Name           Lucario
Type 1        Fighting
Type 2           Steel
HP                  70
Attack             110
Defense             70
Sp. Atk            115
Sp. Def             70
Speed               90
Generation           4
Legendary        False
Name: 497, dtype: object ['Type 1 ']
498 #                             448
Name          LucarioMega Lucario
Type 1                   Fighting
Type 2                      Steel
HP                             70
Attack                        145
Defense                        88
Sp. Atk                       140
Sp. Def                        70
Speed                         112
Generation                      4
Legendary                   False
Name: 498, dtype: object ['Type 1 ']
499 #                    449
Name          Hippopotas
Type 1            Ground
Type 2               NaN
HP                    68
Attack                72
Defense               78
Sp. Atk               38
Sp. Def               42
Speed                 32
Generation             4
Legendary          False
Name: 499, dtype: object ['Type 1 ']
500 #                   450
Name          Hippowdon
Type 1           Ground
Type 2              NaN
HP                  108
Attack              112
Defense             118
Sp. Atk              68
Sp. Def              72
Speed                47
Generation            4
Legendary         False
Name: 500, dtype: object ['Type 1 ']
501 #                 451
Name          Skorupi
Type 1         Poison
Type 2            Bug
HP                 40
Attack             50
Defense            90
Sp. Atk            30
Sp. Def            55
Speed              65
Generation          4
Legendary       False
Name: 501, dtype: object ['Type 1 ']
502 #                 452
Name          Drapion
Type 1         Poison
Type 2           Dark
HP                 70
Attack             90
Defense           110
Sp. Atk            60
Sp. Def            75
Speed              95
Generation          4
Legendary       False
Name: 502, dtype: object ['Type 1 ']
503 #                  453
Name          Croagunk
Type 1          Poison
Type 2        Fighting
HP                  48
Attack              61
Defense             40
Sp. Atk             61
Sp. Def             40
Speed               50
Generation           4
Legendary        False
Name: 503, dtype: object ['Type 1 ']
504 #                   454
Name          Toxicroak
Type 1           Poison
Type 2         Fighting
HP                   83
Attack              106
Defense              65
Sp. Atk              86
Sp. Def              65
Speed                85
Generation            4
Legendary         False
Name: 504, dtype: object ['Type 1 ']
505 #                   455
Name          Carnivine
Type 1            Grass
Type 2              NaN
HP                   74
Attack              100
Defense              72
Sp. Atk              90
Sp. Def              72
Speed                46
Generation            4
Legendary         False
Name: 505, dtype: object ['Type 1 ']
506 #                 456
Name          Finneon
Type 1          Water
Type 2            NaN
HP                 49
Attack             49
Defense            56
Sp. Atk            49
Sp. Def            61
Speed              66
Generation          4
Legendary       False
Name: 506, dtype: object ['Type 1 ']
507 #                  457
Name          Lumineon
Type 1           Water
Type 2             NaN
HP                  69
Attack              69
Defense             76
Sp. Atk             69
Sp. Def             86
Speed               91
Generation           4
Legendary        False
Name: 507, dtype: object ['Type 1 ']
508 #                 458
Name          Mantyke
Type 1          Water
Type 2         Flying
HP                 45
Attack             20
Defense            50
Sp. Atk            60
Sp. Def           120
Speed              50
Generation          4
Legendary       False
Name: 508, dtype: object ['Type 1 ']
509 #                459
Name          Snover
Type 1         Grass
Type 2           Ice
HP                60
Attack            62
Defense           50
Sp. Atk           62
Sp. Def           60
Speed             40
Generation         4
Legendary      False
Name: 509, dtype: object ['Type 1 ']
510 #                   460
Name          Abomasnow
Type 1            Grass
Type 2              Ice
HP                   90
Attack               92
Defense              75
Sp. Atk              92
Sp. Def              85
Speed                60
Generation            4
Legendary         False
Name: 510, dtype: object ['Type 1 ']
511 #                                 460
Name          AbomasnowMega Abomasnow
Type 1                          Grass
Type 2                            Ice
HP                                 90
Attack                            132
Defense                           105
Sp. Atk                           132
Sp. Def                           105
Speed                              30
Generation                          4
Legendary                       False
Name: 511, dtype: object ['Type 1 ']
512 #                 461
Name          Weavile
Type 1           Dark
Type 2            Ice
HP                 70
Attack            120
Defense            65
Sp. Atk            45
Sp. Def            85
Speed             125
Generation          4
Legendary       False
Name: 512, dtype: object ['Type 1 ']
513 #                   462
Name          Magnezone
Type 1         Electric
Type 2            Steel
HP                   70
Attack               70
Defense             115
Sp. Atk             130
Sp. Def              90
Speed                60
Generation            4
Legendary         False
Name: 513, dtype: object ['Type 1 ']
514 #                    463
Name          Lickilicky
Type 1            Normal
Type 2               NaN
HP                   110
Attack                85
Defense               95
Sp. Atk               80
Sp. Def               95
Speed                 50
Generation             4
Legendary          False
Name: 514, dtype: object ['Type 1 ']
515 #                   464
Name          Rhyperior
Type 1           Ground
Type 2             Rock
HP                  115
Attack              140
Defense             130
Sp. Atk              55
Sp. Def              55
Speed                40
Generation            4
Legendary         False
Name: 515, dtype: object ['Type 1 ']
516 #                   465
Name          Tangrowth
Type 1            Grass
Type 2              NaN
HP                  100
Attack              100
Defense             125
Sp. Atk             110
Sp. Def              50
Speed                50
Generation            4
Legendary         False
Name: 516, dtype: object ['Type 1 ']
517 #                    466
Name          Electivire
Type 1          Electric
Type 2               NaN
HP                    75
Attack               123
Defense               67
Sp. Atk               95
Sp. Def               85
Speed                 95
Generation             4
Legendary          False
Name: 517, dtype: object ['Type 1 ']
518 #                   467
Name          Magmortar
Type 1             Fire
Type 2              NaN
HP                   75
Attack               95
Defense              67
Sp. Atk             125
Sp. Def              95
Speed                83
Generation            4
Legendary         False
Name: 518, dtype: object ['Type 1 ']
519 #                  468
Name          Togekiss
Type 1           Fairy
Type 2          Flying
HP                  85
Attack              50
Defense             95
Sp. Atk            120
Sp. Def            115
Speed               80
Generation           4
Legendary        False
Name: 519, dtype: object ['Type 1 ']
520 #                 469
Name          Yanmega
Type 1            Bug
Type 2         Flying
HP                 86
Attack             76
Defense            86
Sp. Atk           116
Sp. Def            56
Speed              95
Generation          4
Legendary       False
Name: 520, dtype: object ['Type 1 ']
521 #                 470
Name          Leafeon
Type 1          Grass
Type 2            NaN
HP                 65
Attack            110
Defense           130
Sp. Atk            60
Sp. Def            65
Speed              95
Generation          4
Legendary       False
Name: 521, dtype: object ['Type 1 ']
522 #                 471
Name          Glaceon
Type 1            Ice
Type 2            NaN
HP                 65
Attack             60
Defense           110
Sp. Atk           130
Sp. Def            95
Speed              65
Generation          4
Legendary       False
Name: 522, dtype: object ['Type 1 ']
523 #                 472
Name          Gliscor
Type 1         Ground
Type 2         Flying
HP                 75
Attack             95
Defense           125
Sp. Atk            45
Sp. Def            75
Speed              95
Generation          4
Legendary       False
Name: 523, dtype: object ['Type 1 ']
524 #                   473
Name          Mamoswine
Type 1              Ice
Type 2           Ground
HP                  110
Attack              130
Defense              80
Sp. Atk              70
Sp. Def              60
Speed                80
Generation            4
Legendary         False
Name: 524, dtype: object ['Type 1 ']
525 #                   474
Name          Porygon-Z
Type 1           Normal
Type 2              NaN
HP                   85
Attack               80
Defense              70
Sp. Atk             135
Sp. Def              75
Speed                90
Generation            4
Legendary         False
Name: 525, dtype: object ['Type 1 ']
526 #                  475
Name           Gallade
Type 1         Psychic
Type 2        Fighting
HP                  68
Attack             125
Defense             65
Sp. Atk             65
Sp. Def            115
Speed               80
Generation           4
Legendary        False
Name: 526, dtype: object ['Type 1 ']
527 #                             475
Name          GalladeMega Gallade
Type 1                    Psychic
Type 2                   Fighting
HP                             68
Attack                        165
Defense                        95
Sp. Atk                        65
Sp. Def                       115
Speed                         110
Generation                      4
Legendary                   False
Name: 527, dtype: object ['Type 1 ']
528 #                   476
Name          Probopass
Type 1             Rock
Type 2            Steel
HP                   60
Attack               55
Defense             145
Sp. Atk              75
Sp. Def             150
Speed                40
Generation            4
Legendary         False

Name: 693, dtype: object ['Type 1 ']
694 #                633
Name           Deino
Type 1          Dark
Type 2        Dragon
HP                52
Attack            65
Defense           50
Sp. Atk           45
Sp. Def           50
Speed             38
Generation         5
Legendary      False
Name: 694, dtype: object ['Type 1 ']
695 #                  634
Name          Zweilous
Type 1            Dark
Type 2          Dragon
HP                  72
Attack              85
Defense             70
Sp. Atk             65
Sp. Def             70
Speed               58
Generation           5
Legendary        False
Name: 695, dtype: object ['Type 1 ']
696 #                   635
Name          Hydreigon
Type 1             Dark
Type 2           Dragon
HP                   92
Attack              105
Defense              90
Sp. Atk             125
Sp. Def              90
Speed                98
Generation            5
Legendary         False
Name: 696, dtype: object ['Type 1 ']
697 #                  636
Name          Larvesta
Type 1             Bug
Type 2            Fire
HP                  55
Attack              85
Defense             55
Sp. Atk             50
Sp. Def             55
Speed               60
Generation           5
Legendary        False
Name: 697, dtype: object ['Type 1 ']
698 #                   637
Name          Volcarona
Type 1              Bug
Type 2             Fire
HP                   85
Attack               60
Defense              65
Sp. Atk             135
Sp. Def             105
Speed               100
Generation            5
Legendary         False
Name: 698, dtype: object ['Type 1 ']
699 #                  638
Name          Cobalion
Type 1           Steel
Type 2        Fighting
HP                  91
Attack              90
Defense            129
Sp. Atk             90
Sp. Def             72
Speed              108
Generation           5
Legendary         True
Name: 699, dtype: object ['Type 1 ']
700 #                   639
Name          Terrakion
Type 1             Rock
Type 2         Fighting
HP                   91
Attack              129
Defense              90
Sp. Atk              72
Sp. Def              90
Speed               108
Generation            5
Legendary          True
Name: 700, dtype: object ['Type 1 ']
701 #                  640
Name          Virizion
Type 1           Grass
Type 2        Fighting
HP                  91
Attack              90
Defense             72
Sp. Atk             90
Sp. Def            129
Speed              108
Generation           5
Legendary         True
Name: 701, dtype: object ['Type 1 ']
702 #                                 641
Name          TornadusIncarnate Forme
Type 1                         Flying
Type 2                            NaN
HP                                 79
Attack                            115
Defense                            70
Sp. Atk                           125
Sp. Def                            80
Speed                             111
Generation                          5
Legendary                        True
Name: 702, dtype: object ['Type 1 ']
703 #                               641
Name          TornadusTherian Forme
Type 1                       Flying
Type 2                          NaN
HP                               79
Attack                          100
Defense                          80
Sp. Atk                         110
Sp. Def                          90
Speed                           121
Generation                        5
Legendary                      True
Name: 703, dtype: object ['Type 1 ']
704 #                                  642
Name          ThundurusIncarnate Forme
Type 1                        Electric
Type 2                          Flying
HP                                  79
Attack                             115
Defense                             70
Sp. Atk                            125
Sp. Def                             80
Speed                              111
Generation                           5
Legendary                         True
Name: 704, dtype: object ['Type 1 ']
705 #                                642
Name          ThundurusTherian Forme
Type 1                      Electric
Type 2                        Flying
HP                                79
Attack                           105
Defense                           70
Sp. Atk                          145
Sp. Def                           80
Speed                            101
Generation                         5
Legendary                       True
Name: 705, dtype: object ['Type 1 ']
706 #                  643
Name          Reshiram
Type 1          Dragon
Type 2            Fire
HP                 100
Attack             120
Defense            100
Sp. Atk            150
Sp. Def            120
Speed               90
Generation           5
Legendary         True
Name: 706, dtype: object ['Type 1 ']
707 #                  644
Name            Zekrom
Type 1          Dragon
Type 2        Electric
HP                 100
Attack             150
Defense            120
Sp. Atk            120
Sp. Def            100
Speed               90
Generation           5
Legendary         True
Name: 707, dtype: object ['Type 1 ']
708 #                                 645
Name          LandorusIncarnate Forme
Type 1                         Ground
Type 2                         Flying
HP                                 89
Attack                            125
Defense                            90
Sp. Atk                           115
Sp. Def                            80
Speed                             101
Generation                          5
Legendary                        True
Name: 708, dtype: object ['Type 1 ']
709 #                               645
Name          LandorusTherian Forme
Type 1                       Ground
Type 2                       Flying
HP                               89
Attack                          145
Defense                          90
Sp. Atk                         105
Sp. Def                          80
Speed                            91
Generation                        5
Legendary                      True
Name: 709, dtype: object ['Type 1 ']
710 #                646
Name          Kyurem
Type 1        Dragon
Type 2           Ice
HP               125
Attack           130
Defense           90
Sp. Atk          130
Sp. Def           90
Speed             95
Generation         5
Legendary       True
Name: 710, dtype: object ['Type 1 ']
711 #                            646
Name          KyuremBlack Kyurem
Type 1                    Dragon
Type 2                       Ice
HP                           125
Attack                       170
Defense                      100
Sp. Atk                      120
Sp. Def                       90
Speed                         95
Generation                     5
Legendary                   True
Name: 711, dtype: object ['Type 1 ']
712 #                            646
Name          KyuremWhite Kyurem
Type 1                    Dragon
Type 2                       Ice
HP                           125
Attack                       120
Defense                       90
Sp. Atk                      170
Sp. Def                      100
Speed                         95
Generation                     5
Legendary                   True
Name: 712, dtype: object ['Type 1 ']
713 #                              647
Name          KeldeoOrdinary Forme
Type 1                       Water
Type 2                    Fighting
HP                              91
Attack                          72
Defense                         90
Sp. Atk                        129
Sp. Def                         90
Speed                          108
Generation                       5
Legendary                    False
Name: 713, dtype: object ['Type 1 ']
714 #                              647
Name          KeldeoResolute Forme
Type 1                       Water
Type 2                    Fighting
HP                              91
Attack                          72
Defense                         90
Sp. Atk                        129
Sp. Def                         90
Speed                          108
Generation                       5
Legendary                    False
Name: 714, dtype: object ['Type 1 ']
715 #                            648
Name          MeloettaAria Forme
Type 1                    Normal
Type 2                   Psychic
HP                           100
Attack                        77
Defense                       77
Sp. Atk                      128
Sp. Def                      128
Speed                         90
Generation                     5
Legendary                  False
Name: 715, dtype: object ['Type 1 ']
716 #                                 648
Name          MeloettaPirouette Forme
Type 1                         Normal
Type 2                       Fighting
HP                                100
Attack                            128
Defense                            90
Sp. Atk                            77
Sp. Def                            77
Speed                             128
Generation                          5
Legendary                       False
Name: 716, dtype: object ['Type 1 ']
717 #                  649
Name          Genesect
Type 1             Bug
Type 2           Steel
HP                  71
Attack             120
Defense             95
Sp. Atk            120
Sp. Def             95
Speed               99
Generation           5
Legendary        False
Name: 717, dtype: object ['Type 1 ']
718 #                 650
Name          Chespin
Type 1          Grass
Type 2            NaN
HP                 56
Attack             61
Defense            65
Sp. Atk            48
Sp. Def            45
Speed              38
Generation          6
Legendary       False
Name: 718, dtype: object ['Type 1 ']
719 #                   651
Name          Quilladin
Type 1            Grass
Type 2              NaN
HP                   61
Attack               78
Defense              95
Sp. Atk              56
Sp. Def              58
Speed                57
Generation            6
Legendary         False
Name: 719, dtype: object ['Type 1 ']
720 #                    652
Name          Chesnaught
Type 1             Grass
Type 2          Fighting
HP                    88
Attack               107
Defense              122
Sp. Atk               74
Sp. Def               75
Speed                 64
Generation             6
Legendary          False
Name: 720, dtype: object ['Type 1 ']
721 #                  653
Name          Fennekin
Type 1            Fire
Type 2             NaN
HP                  40
Attack              45
Defense             40
Sp. Atk             62
Sp. Def             60
Speed               60
Generation           6
Legendary        False
Name: 721, dtype: object ['Type 1 ']
722 #                 654
Name          Braixen
Type 1           Fire
Type 2            NaN
HP                 59
Attack             59
Defense            58
Sp. Atk            90
Sp. Def            70
Speed              73
Generation          6
Legendary       False
Name: 722, dtype: object ['Type 1 ']
723 #                 655
Name          Delphox
Type 1           Fire
Type 2        Psychic
HP                 75
Attack             69
Defense            72
Sp. Atk           114
Sp. Def           100
Speed             104
Generation          6
Legendary       False
Name: 723, dtype: object ['Type 1 ']
724 #                 656
Name          Froakie
Type 1          Water
Type 2            NaN
HP                 41
Attack             56
Defense            40
Sp. Atk            62
Sp. Def            44
Speed              71
Generation          6
Legendary       False
Name: 724, dtype: object ['Type 1 ']
725 #                   657
Name          Frogadier
Type 1            Water
Type 2              NaN
HP                   54
Attack               63
Defense              52
Sp. Atk              83
Sp. Def              56
Speed                97
Generation            6
Legendary         False
Name: 725, dtype: object ['Type 1 ']
726 #                  658
Name          Greninja
Type 1           Water
Type 2            Dark
HP                  72
Attack              95
Defense             67
Sp. Atk            103
Sp. Def             71
Speed              122
Generation           6
Legendary        False
Name: 726, dtype: object ['Type 1 ']
727 #                  659
Name          Bunnelby
Type 1          Normal
Type 2             NaN
HP                  38
Attack              36
Defense             38
Sp. Atk             32
Sp. Def             36
Speed               57
Generation           6
Legendary        False
Name: 727, dtype: object ['Type 1 ']
728 #                   660
Name          Diggersby
Type 1           Normal
Type 2           Ground
HP                   85
Attack               56
Defense              77
Sp. Atk              50
Sp. Def              77
Speed                78
Generation            6
Legendary         False
Name: 728, dtype: object ['Type 1 ']
729 #                    661
Name          Fletchling
Type 1            Normal
Type 2            Flying
HP                    45
Attack                50
Defense               43
Sp. Atk               40
Sp. Def               38
Speed                 62
Generation             6
Legendary          False
Name: 729, dtype: object ['Type 1 ']
730 #                     662
Name          Fletchinder
Type 1               Fire
Type 2             Flying
HP                     62
Attack                 73
Defense                55
Sp. Atk                56
Sp. Def                52
Speed                  84
Generation              6
Legendary           False
Name: 730, dtype: object ['Type 1 ']
731 #                    663
Name          Talonflame
Type 1              Fire
Type 2            Flying
HP                    78
Attack                81
Defense               71
Sp. Atk               74
Sp. Def               69
Speed                126
Generation             6
Legendary          False
Name: 731, dtype: object ['Type 1 ']
732 #                    664
Name          Scatterbug
Type 1               Bug
Type 2               NaN
HP                    38
Attack                35
Defense               40
Sp. Atk               27
Sp. Def               25
Speed                 35
Generation             6
Legendary          False
Name: 732, dtype: object ['Type 1 ']
733 #                665
Name          Spewpa
Type 1           Bug
Type 2           NaN
HP                45
Attack            22
Defense           60
Sp. Atk           27
Sp. Def           30
Speed             29
Generation         6
Legendary      False
Name: 733, dtype: object ['Type 1 ']
734 #                  666
Name          Vivillon
Type 1             Bug
Type 2          Flying
HP                  80
Attack              52
Defense             50
Sp. Atk             90
Sp. Def             50
Speed               89
Generation           6
Legendary        False
Name: 734, dtype: object ['Type 1 ']
735 #                667
Name          Litleo
Type 1          Fire
Type 2        Normal
HP                62
Attack            50
Defense           58
Sp. Atk           73
Sp. Def           54
Speed             72
Generation         6
Legendary      False
Name: 735, dtype: object ['Type 1 ']
736 #                668
Name          Pyroar
Type 1          Fire
Type 2        Normal
HP                86
Attack            68
Defense           72
Sp. Atk          109
Sp. Def           66
Speed            106
Generation         6
Legendary      False
Name: 736, dtype: object ['Type 1 ']
737 #                 669
Name          FlabÃ©bÃ©
Type 1          Fairy
Type 2            NaN
HP                 44
Attack             38
Defense            39
Sp. Atk            61
Sp. Def            79
Speed              42
Generation          6
Legendary       False
Name: 737, dtype: object ['Type 1 ']
738 #                 670
Name          Floette
Type 1          Fairy
Type 2            NaN
HP                 54
Attack             45
Defense            47
Sp. Atk            75
Sp. Def            98
Speed              52
Generation          6
Legendary       False
Name: 738, dtype: object ['Type 1 ']
739 #                 671
Name          Florges
Type 1          Fairy
Type 2            NaN
HP                 78
Attack             65
Defense            68
Sp. Atk           112
Sp. Def           154
Speed              75
Generation          6
Legendary       False
Name: 739, dtype: object ['Type 1 ']
740 #                672
Name          Skiddo
Type 1         Grass
Type 2           NaN
HP                66
Attack            65
Defense           48
Sp. Atk           62
Sp. Def           57
Speed             52
Generation         6
Legendary      False
Name: 740, dtype: object ['Type 1 ']
741 #                673
Name          Gogoat
Type 1         Grass
Type 2           NaN
HP               123
Attack           100
Defense           62
Sp. Atk           97
Sp. Def           81
Speed             68
Generation         6
Legendary      False
Name: 741, dtype: object ['Type 1 ']
742 #                  674
Name           Pancham
Type 1        Fighting
Type 2             NaN
HP                  67
Attack              82
Defense             62
Sp. Atk             46
Sp. Def             48
Speed               43
Generation           6
Legendary        False
Name: 742, dtype: object ['Type 1 ']
743 #                  675
Name           Pangoro
Type 1        Fighting
Type 2            Dark
HP                  95
Attack             124
Defense             78
Sp. Atk             69
Sp. Def             71
Speed               58
Generation           6
Legendary        False
Name: 743, dtype: object ['Type 1 ']
744 #                 676
Name          Furfrou
Type 1         Normal
Type 2            NaN
HP                 75
Attack             80
Defense            60
Sp. Atk            65
Sp. Def            90
Speed             102
Generation          6
Legendary       False
Name: 744, dtype: object ['Type 1 ']
745 #                 677
Name           Espurr
Type 1        Psychic
Type 2            NaN
HP                 62
Attack             48
Defense            54
Sp. Atk            63
Sp. Def            60
Speed              68
Generation          6
Legendary       False
Name: 745, dtype: object ['Type 1 ']
746 #                      678
Name          MeowsticMale
Type 1             Psychic
Type 2                 NaN
HP                      74
Attack                  48
Defense                 76
Sp. Atk                 83
Sp. Def                 81
Speed                  104
Generation               6
Legendary            False
Name: 746, dtype: object ['Type 1 ']
747 #                        678
Name          MeowsticFemale
Type 1               Psychic
Type 2                   NaN
HP                        74
Attack                    48
Defense                   76
Sp. Atk                   83
Sp. Def                   81
Speed                    104
Generation                 6
Legendary              False
Name: 747, dtype: object ['Type 1 ']
748 #                 679
Name          Honedge
Type 1          Steel
Type 2          Ghost
HP                 45
Attack             80
Defense           100
Sp. Atk            35
Sp. Def            37
Speed              28
Generation          6
Legendary       False
Name: 748, dtype: object ['Type 1 ']
749 #                  680
Name          Doublade
Type 1           Steel
Type 2           Ghost
HP                  59
Attack             110
Defense            150
Sp. Atk             45
Sp. Def             49
Speed               35
Generation           6
Legendary        False
Name: 749, dtype: object ['Type 1 ']
750 #                              681
Name          AegislashBlade Forme
Type 1                       Steel
Type 2                       Ghost
HP                              60
Attack                         150
Defense                         50
Sp. Atk                        150

In [81]:
df.loc[df['Type 2'] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
246,228,Houndour,Dark,Fire,45,60,30,80,50,65,2,False
247,229,Houndoom,Dark,Fire,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
532,479,RotomHeat Rotom,Electric,Fire,50,65,107,105,107,86,4,False
553,494,Victini,Psychic,Fire,100,100,100,100,100,100,5,True
668,607,Litwick,Ghost,Fire,50,30,55,65,55,20,5,False
669,608,Lampent,Ghost,Fire,60,40,60,95,60,55,5,False
670,609,Chandelure,Ghost,Fire,60,55,90,145,90,80,5,False
697,636,Larvesta,Bug,Fire,55,85,55,50,55,60,5,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
706,643,Reshiram,Dragon,Fire,100,120,100,150,120,90,5,True

In [85]:
df.loc[df['Type 2']== "Poison"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
53,48,Venonat,Bug,Poison,60,55,50,40,55,45,1,False
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False
79,73,Tentacruel,Water,Poison,80,70,65,80,120,100,1,False
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
227,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False
292,269,Dustox,Bug,Poison,60,50,70,50,90,65,3,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [86]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [88]:
df.loc[df['Attack']==100]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
33,28,Sandslash,Ground,NaN,75,100,110,45,55,65,1,False
73,67,Machoke,Fighting,NaN,80,100,70,50,60,45,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
138,128,Tauros,Normal,NaN,75,100,95,40,70,110,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
165,151,Mew,Psychic,NaN,100,100,100,100,100,100,1,False
200,185,Sudowoodo,Rock,NaN,70,100,115,30,65,30,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
271,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False
298,275,Shiftry,Grass,Dark,90,100,60,90,60,80,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,3,False
361,330,Flygon,Ground,Dragon,80,100,80,80,80,100,3,False
368,336,Seviper,Poison,NaN,73,100,60,100,60,65,3,False
414,377,Regirock,Rock,NaN,80,100,200,50,100,50,3,True
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True
421,382,Kyogre,Water,NaN,100,100,90,150,140,90,3,True
427,385,Jirachi,Steel,Psychic,100,100,100,100,100,100,3,True
471,424,Ambipom,Normal,NaN,75,100,66,60,66,115,4,False
505,455,Carnivine,Grass,NaN,74,100,72,90,72,46,4,False
516,465,Tangrowth,Grass,NaN,100,100,125,110,50,50,4,False
529,477,Dusknoir,Ghost,NaN,45,100,135,65,135,45,4,False
544,487,GiratinaAltered Forme,Ghost,Dragon,150,100,120,100,120,90,4,True
548,490,Manaphy,Water,NaN,100,100,100,100,100,100,4,False
550,492,ShayminLand Forme,Grass,NaN,100,100,100,100,100,100,4,True
553,494,Victini,Psychic,Fire,100,100,100,100,100,100,5,True
562,503,Samurott,Water,NaN,95,100,85,108,70,70,5,False
582,523,Zebstrika,Electric,NaN,75,100,63,80,63,116,5,False
598,538,Throh,Fighting,NaN,120,100,85,30,85,45,5,False
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False
647,586,Sawsbuck,Normal,Grass,80,100,70,60,70,95,5,False
662,601,Klinklang,Steel,NaN,60,100,115,70,85,90,5,False
703,641,TornadusTherian Forme,Flying,NaN,79,100,80,110,90,121,5,True
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False
776,706,Goodra,Dragon,NaN,90,100,70,110,150,80,6,False
787,711,GourgeistSuper Size,Ghost,Grass,85,100,122,58,75,54,6,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True

In [91]:
df.loc[df['Legendary']==False]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
787,711,GourgeistSuper Size,Ghost,Grass,85,100,122,58,75,54,6,False
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False
790,714,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False

In [92]:
df.loc[df['Type 1']=="Ghost"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
215,200,Misdreavus,Ghost,NaN,60,60,60,85,85,85,2,False
385,353,Shuppet,Ghost,NaN,44,75,35,63,33,45,3,False
386,354,Banette,Ghost,NaN,64,115,65,83,63,65,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False
388,355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False
389,356,Dusclops,Ghost,NaN,40,70,130,60,130,25,3,False
472,425,Drifloon,Ghost,Flying,90,50,34,60,44,70,4,False
473,426,Drifblim,Ghost,Flying,150,80,44,90,54,80,4,False
477,429,Mismagius,Ghost,NaN,60,60,60,105,105,105,4,False
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,4,False
529,477,Dusknoir,Ghost,NaN,45,100,135,65,135,45,4,False
544,487,GiratinaAltered Forme,Ghost,Dragon,150,100,120,100,120,90,4,True
545,487,GiratinaOrigin Forme,Ghost,Dragon,150,120,100,120,100,90,4,True
623,562,Yamask,Ghost,NaN,38,30,85,55,65,30,5,False
624,563,Cofagrigus,Ghost,NaN,58,50,145,95,105,30,5,False
668,607,Litwick,Ghost,Fire,50,30,55,65,55,20,5,False
669,608,Lampent,Ghost,Fire,60,40,60,95,60,55,5,False
670,609,Chandelure,Ghost,Fire,60,55,90,145,90,80,5,False
778,708,Phantump,Ghost,Grass,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,85,100,122,58,75,54,6,False

In [93]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [95]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [96]:
df.sort_values('Attack')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True

In [108]:
df.sort_values('Name',ascending=True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [110]:

df.sort_values('Name',ascending=True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [115]:
df.sort_values('Attack',ascending=True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True

In [118]:
df.sort_values('Defense')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
188,174,Igglybuff,Normal,Fairy,90,30,15,40,20,15,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
414,377,Regirock,Rock,NaN,80,100,200,50,100,50,3,True
223,208,Steelix,Steel,Ground,75,85,200,55,65,30,2,False
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False

In [121]:
df.sort_values(['Name','Attack'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [122]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [125]:
df.sort_values(['Name','HP'],ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [134]:
df['total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Speed']
df['total']

0      253
1      325
2      425
3      505
4      259
      ...
795    450
796    590
797    470
798    550
799    510
Name: total, Length: 800, dtype: int64

In [135]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,253
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,325
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,425
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,505
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,259

In [138]:
df.pop('total')

0      253
1      325
2      425
3      505
4      259
      ...
795    450
796    590
797    470
798    550
799    510
Name: total, Length: 800, dtype: int64

In [139]:
df.head(4)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [140]:
df=df.drop(columns=['Generation'])

In [141]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False
...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True

In [154]:
df['total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
df['total']

0      318
1      405
2      525
3      625
4      309
      ...
795    600
796    700
797    600
798    680
799    600
Name: total, Length: 800, dtype: int64

In [164]:
df['total']
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,NaN
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,NaN
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,NaN

In [159]:
df['total']=df.iloc[:,4:6].sum(axis=0)

In [161]:
df['total']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
795   NaN
796   NaN
797   NaN
798   NaN
799   NaN
Name: total, Length: 800, dtype: float64

In [162]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,NaN
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,NaN
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,NaN

In [163]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,NaN
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,NaN

In [165]:
df['total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
df['total']

0      318
1      405
2      525
3      625
4      309
      ...
795    600
796    700
797    600
798    680
799    600
Name: total, Length: 800, dtype: int64

In [166]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [177]:
df.to_csv('modified.csv',index=False)

In [178]:
sd=pd.read_csv('modified.csv')

In [179]:
sd

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [184]:
df.loc[df['Type 1']=="Grass"[0:5]]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,False,320
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,False,313
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,False,405
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,False,530
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,False,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,False,531

In [188]:
df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,False,320
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,False,395
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,False,490
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,False,300
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,False,390
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,False,490
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,False,400
451,406,Budew,Grass,Poison,40,30,35,50,70,55,False,280
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,False,515
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,False,294
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,False,464

In [191]:
df.loc[(df['HP']==50)| (df['Legendary']==False)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,False,514
790,714,Noibat,Flying,Dragon,40,30,35,45,40,55,False,245
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,False,535
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700

In [202]:
new_df=df.loc[(df['Type 1']=='Rock') & (df['Type 2']=='Dark')]

In [203]:
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
267,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,False,600
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,False,700

In [204]:
new_df.to_csv('new_df.csv')

In [205]:
xz=pd.read_csv('new_df.csv')

In [206]:
xz

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,267,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,False,600
1,268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,False,700

In [207]:
sd

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [208]:
sd=sd.head(6)

In [209]:
sd

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,False,405

In [221]:
sd=sd.reset_index(drop=True)

AttributeError: 'function' object has no attribute 'reset_index'

In [225]:
sd.head(1)

AttributeError: 'function' object has no attribute 'head'

In [226]:
sd

<bound method DataFrame.reset_index of    #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60
5  5             Charmeleon   Fire     NaN  58      64       58       80

   Sp. Def  Speed  Legendary  total
0       65     45      False    318
1       80     60      False    405
2      100     80      False    525
3      120     80      False    625
4       50     65      False    309
5       65     80      False    405  >

In [324]:
m=df.loc[df['Name'].str.contains('Venusaur')]

AttributeError: 'str' object has no attribute 'loc'

In [242]:
m

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625

In [256]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,True,600
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [249]:
m

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
2,3,Grass,Poison,80,82,83,100,100,80,False,525
3,3,Grass,Poison,80,100,123,122,120,80,False,625

In [262]:
import re

df.loc[df['Name'].str.contains('Mega',regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,False,634
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,False,630
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,False,495
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,False,579
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,False,590
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,False,590
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,False,600
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,False,590
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,False,600
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,False,640
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,False,615
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,True,780
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,True,780
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,False,525
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,False,610
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,False,610
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,False,600
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,False,600
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,False,600
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,False,700
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,False,630
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,False,630
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,False,635
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,False,618
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,False,480
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,False,480
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,False,630
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,False,510
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,False,575
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,False,560
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,False,560
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,False,590
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,False,555
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,False,565
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,False,580
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,False,700
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,False,700
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,True,700
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,True,700
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,True,780
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,False,580
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,False,700
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,False,625
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,False,594
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,False,618
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,False,545
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700

In [268]:
import re 
df.loc[df['Type 1'].str.contains('Fire|Grass',regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,False,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,False,507
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,False,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,False,531
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [271]:
import re
df.loc[df['Type 1'].str.contains('Fire|Grass',regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,False,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,False,507
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,False,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,False,531
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [275]:
import re
n=df.loc[df['Type 1'].str.contains('fire|grass',flags=re.I,regex=True)]

In [280]:
n1=n.head(6)

In [281]:
n1

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,False,405

In [285]:
import re
l=df.loc[df['Type 1'].str.contains('fire|grass',flags=re.I,regex=True)]

In [286]:
l.head(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,False,405
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,False,534
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,False,634
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,False,299

In [288]:
df.pop('total')

0      318
1      405
2      525
3      625
4      309
      ...
795    600
796    700
797    600
798    680
799    600
Name: total, Length: 800, dtype: int64

In [321]:
import pandas as pd

In [322]:
import re
x=df.loc[df['Name'].str.contains('^ka[a-z]*',flags=re.I,regex=True)]
x

AttributeError: 'str' object has no attribute 'loc'

In [345]:
df.loc[df['Type 1']=='Rock','Type 1']=='Stone'
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,king,80,82,83,100,100,80,testvalue,525
3,3,VenusaurMega Venusaur,Grass,king,80,100,123,122,120,80,testvalue,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,king,50,100,150,100,150,50,testvalue,600
796,719,DiancieMega Diancie,Rock,king,50,160,110,160,110,110,testvalue,700
797,720,HoopaHoopa Confined,Psychic,king,80,110,60,150,130,70,testvalue,600
798,720,HoopaHoopa Unbound,Psychic,king,80,160,60,170,130,80,testvalue,680
799,721,Volcanion,Fire,king,80,110,120,130,90,70,testvalue,600

In [346]:
df.loc[df['Type 1']=='Fire','Type 1']

4      Fire
5      Fire
6      Fire
7      Fire
8      Fire
42     Fire
43     Fire
63     Fire
64     Fire
83     Fire
84     Fire
135    Fire
147    Fire
158    Fire
169    Fire
170    Fire
171    Fire
236    Fire
237    Fire
259    Fire
263    Fire
270    Fire
276    Fire
277    Fire
278    Fire
279    Fire
352    Fire
353    Fire
354    Fire
355    Fire
435    Fire
436    Fire
437    Fire
518    Fire
542    Fire
557    Fire
558    Fire
559    Fire
572    Fire
573    Fire
614    Fire
615    Fire
616    Fire
692    Fire
721    Fire
722    Fire
723    Fire
730    Fire
731    Fire
735    Fire
736    Fire
799    Fire
Name: Type 1, dtype: object

In [325]:
df=pd.read_csv('modified.csv')

In [326]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [328]:
df.loc[df['total']<400]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,False,314
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,False,195
14,11,Metapod,Bug,NaN,50,20,55,25,25,30,False,205
...,...,...,...,...,...,...,...,...,...,...,...,...
781,710,PumpkabooSmall Size,Ghost,Grass,44,66,70,44,55,56,False,335
782,710,PumpkabooLarge Size,Ghost,Grass,54,66,70,44,55,46,False,335
783,710,PumpkabooSuper Size,Ghost,Grass,59,66,70,44,55,41,False,335
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,False,304
790,714,Noibat,Flying,Dragon,40,30,35,45,40,55,False,245

In [344]:
df.loc[df['total']>500,['Legendary']]='testvalue'
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,king,80,82,83,100,100,80,testvalue,525
3,3,VenusaurMega Venusaur,Grass,king,80,100,123,122,120,80,testvalue,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,king,50,100,150,100,150,50,testvalue,600
796,719,DiancieMega Diancie,Rock,king,50,160,110,160,110,110,testvalue,700
797,720,HoopaHoopa Confined,Psychic,king,80,110,60,150,130,70,testvalue,600
798,720,HoopaHoopa Unbound,Psychic,king,80,160,60,170,130,80,testvalue,680
799,721,Volcanion,Fire,king,80,110,120,130,90,70,testvalue,600

In [342]:
df.loc[df['total'] > 500,['Type 2','Legendary']] = 'king'

In [343]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,king,80,82,83,100,100,80,king,525
3,3,VenusaurMega Venusaur,Grass,king,80,100,123,122,120,80,king,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,king,50,100,150,100,150,50,king,600
796,719,DiancieMega Diancie,Rock,king,50,160,110,160,110,110,king,700
797,720,HoopaHoopa Confined,Psychic,king,80,110,60,150,130,70,king,600
798,720,HoopaHoopa Unbound,Psychic,king,80,160,60,170,130,80,king,680
799,721,Volcanion,Fire,king,80,110,120,130,90,70,king,600

In [351]:
df.loc[df['total'] < 350,['Type 1','Legendary']]=['eww','haha']

In [352]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,eww,Poison,45,49,49,65,65,45,haha,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,king,80,82,83,100,100,80,testvalue,525
3,3,VenusaurMega Venusaur,Grass,king,80,100,123,122,120,80,testvalue,625
4,4,Charmander,eww,NaN,39,52,43,60,50,65,haha,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,king,50,100,150,100,150,50,testvalue,600
796,719,DiancieMega Diancie,Rock,king,50,160,110,160,110,110,testvalue,700
797,720,HoopaHoopa Confined,Psychic,king,80,110,60,150,130,70,testvalue,600
798,720,HoopaHoopa Unbound,Psychic,king,80,160,60,170,130,80,testvalue,680
799,721,Volcanion,Fire,king,80,110,120,130,90,70,testvalue,600

In [353]:
df=pd.read_csv('modified.csv')

In [354]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600

In [360]:
df.groupby('Type 1').mean()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
Type 1,,,,,,,,,
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,0.000000,378.927536
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,0.064516,445.741935
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,0.375000,550.531250
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,0.090909,443.409091
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,0.058824,413.176471
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,0.000000,416.444444
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,0.096154,458.076923
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,0.500000,485.000000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,0.062500,439.562500
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,0.042857,421.142857
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,0.125000,437.500000
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,0.083333,433.458333
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,0.020408,401.683673
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,0.000000,399.142857
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,0.245614,475.947368
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,0.090909,453.750000
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,0.148148,487.703704
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,0.035714,430.455357

In [363]:

df.groupby('Type 1').mean().sort_values('Defense',ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
Type 1,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,0.148148,487.703704
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,0.090909,453.750000
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,0.375000,550.531250
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,0.125000,437.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,0.062500,439.562500
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,0.035714,430.455357
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,0.083333,433.458333
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,0.042857,421.142857
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,0.000000,378.927536
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,0.064516,445.741935
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,0.000000,399.142857
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,0.096154,458.076923
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,0.245614,475.947368
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,0.090909,443.409091
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,0.500000,485.000000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,0.000000,416.444444
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,0.058824,413.176471
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,0.020408,401.683673

In [365]:
df.groupby('Type 1').mean().sort_values('Attack',ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
Type 1,,,,,,,,,
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,0.375000,550.531250
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,0.000000,416.444444
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,0.125000,437.500000
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,0.090909,453.750000
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,0.148148,487.703704
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,0.064516,445.741935
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,0.096154,458.076923
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,0.500000,485.000000
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,0.000000,399.142857
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,0.035714,430.455357
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,0.062500,439.562500
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,0.020408,401.683673
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,0.042857,421.142857
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,0.083333,433.458333
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,0.245614,475.947368
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,0.000000,378.927536
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,0.090909,443.409091
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,0.058824,413.176471

In [369]:
df.groupby('Type 1').count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total
Type 1,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112

In [370]:
df['count']=1

In [373]:
df['itm']='v'

In [374]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,total,count,itm
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,318,1,v
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,405,1,v
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,525,1,v
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,625,1,v
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,309,1,v
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,True,600,1,v
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,True,700,1,v
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,True,600,1,v
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,True,680,1,v
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,True,600,1,v

In [375]:
df.groupby('Type 1').count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [378]:
for df in pd.read_csv('modified.csv',chunksize=500000000):
    print('chunk DF')
    print(df)

chunk DF
       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Legendary  total
0         65       65     45      False    318
1         80       80     60      False    405
2        100      100     80      False    525
3        122      120     80      False    625
4         60       50     65      False    309
..       ...      ...    ...        ...    ...
795      100      150     50       True    600
796      160      110    110       True    700
797      150      130     70       True    600
798      170      130     80       True    680
799      130       90     70       True    600

[800 rows x 12 columns]